###
# Copyright (2016-2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
language: python
python:
  - 3.6.9
  - 3.7
env:
  - ANSIBLE=2.9 PYPI_VERSION='2.9.0.0'  # source code is required to run the sanity test validate-modules
matrix:
  exclude:
  - python: 3.6
    env: ANSIBLE=2.1 PYPI_VERSION='2.1.5.0'
  - python: 3.6
    env: ANSIBLE=2.2 PYPI_VERSION='2.2.2.0'
install:
  - if [[ $PYPI_VERSION ]]; then pip install ansible==$PYPI_VERSION; fi
  - pip install flake8
  - pip install mock
  - pip install git+https://github.com/HewlettPackard/oneview-python.git
  - pip install coveralls
  - pip install hpICsp
  - |
      if [[ $ANSIBLE == 2.1 || $ANSIBLE == 2.2 ]]; then
        pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing;
      fi
before_script:
  - |
      if [[ $BRANCH ]]; then
        git clone -b $BRANCH --single-branch https://github.com/ansible/ansible.git;
        source ./ansible/hacking/env-setup;
        pip install pyyaml jinja2 nose pytest passlib pycrypto six voluptuous;
        ansible-test sanity --test validate-modules;
      fi
script:
  - export ANSIBLE_LIBRARY=$PWD/library
  - export PYTHONPATH=$ANSIBLE_LIBRARY:$PYTHONPATH
  - touch examples/vars/config.yml
  - ./build.sh
