language: python
python:
  - 2.7
  - 3.5
install:
  - pip install ansible==2.1.1.0
  - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
  - pip install flake8
  - pip install mock
  - pip install git+https://github.com/HewlettPackard/python-hpOneView.git
  - pip install coveralls
script:
  - export ANSIBLE_LIBRARY=$PWD/library
  - export PYTHONPATH=$ANSIBLE_LIBRARY:$PYTHONPATH
  - touch examples/vars/config.yml
  - ./build.sh
