---
# Name for the created server profile template
server_profile_template: SPT_sample

# Name for the created server profile
server_profile: serverProfile_sample

# Name of the enclosure group
enclosure_group: EG

# Name of the server hardware type
server_hardware_type: SY 480 Gen10 1

# Name of the server hardware
server_hardware: 0000A66101, bay 11

# Name of the network
network: mgmt
